# 인공지능 과제 - 164202 양진형

### Import module

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn.svm as svm
from sklearn.metrics import confusion_matrix

### Read Data

In [2]:
data = pd.read_csv("iris.csv")
class_name = np.unique(data['variety'])

trainX = data.drop(['variety'], axis=1)
print(class_name)

['Setosa' 'Versicolor' 'Virginica']


## 1. One vs Rest

#### Prepare Train Lebel

In [3]:
trainY_A = np.append(np.ones(50), -np.ones(100))
trainY_B = np.append(-trainY_A[:100], -np.ones(50))
trainY_C = np.append(-np.ones(100), np.ones(50))

#### Make SVM Model and Fit

In [4]:
C = 10

svm_model_A = svm.SVC(kernel = 'linear', C=C).fit(trainX, trainY_A)
svm_model_B = svm.SVC(kernel = 'linear', C=C).fit(trainX, trainY_B)
svm_model_C = svm.SVC(kernel = 'linear', C=C).fit(trainX, trainY_C)

predY_A = svm_model_A.predict(trainX)
predY_B = svm_model_B.predict(trainX)
predY_C = svm_model_C.predict(trainX)

#### Result

In [5]:
# Confusion Matrix 출력
print(confusion_matrix(trainY_A, predY_A))
print(confusion_matrix(trainY_B, predY_B))
print(confusion_matrix(trainY_C, predY_C))

[[100   0]
 [  0  50]]
[[86 14]
 [26 24]]
[[97  3]
 [ 0 50]]


In [6]:
# 멀티클래스에 대해 분류
output_A = svm_model_A.decision_function(trainX)
output_B = svm_model_B.decision_function(trainX)
output_C = svm_model_C.decision_function(trainX)

output = np.reshape(np.concatenate((output_A, output_B, output_C), axis=0), (3, 150)).T

for i in range(output.shape[0]):
    print("%3d: %10s" %(i ,class_name[np.argmax(output[i])]), end=", ")
    
    if (i+1) % 5 == 0:
        print("")
        if (i+1) % 50 == 0:
            print("")

  0:     Setosa,   1:     Setosa,   2:     Setosa,   3:     Setosa,   4:     Setosa, 
  5:     Setosa,   6:     Setosa,   7:     Setosa,   8:     Setosa,   9:     Setosa, 
 10:     Setosa,  11:     Setosa,  12:     Setosa,  13:     Setosa,  14:     Setosa, 
 15:     Setosa,  16:     Setosa,  17:     Setosa,  18:     Setosa,  19:     Setosa, 
 20:     Setosa,  21:     Setosa,  22:     Setosa,  23:     Setosa,  24:     Setosa, 
 25:     Setosa,  26:     Setosa,  27:     Setosa,  28:     Setosa,  29:     Setosa, 
 30:     Setosa,  31:     Setosa,  32:     Setosa,  33:     Setosa,  34:     Setosa, 
 35:     Setosa,  36:     Setosa,  37:     Setosa,  38:     Setosa,  39:     Setosa, 
 40:     Setosa,  41:     Setosa,  42:     Setosa,  43:     Setosa,  44:     Setosa, 
 45:     Setosa,  46:     Setosa,  47:     Setosa,  48:     Setosa,  49:     Setosa, 

 50: Versicolor,  51: Versicolor,  52: Versicolor,  53: Versicolor,  54: Versicolor, 
 55: Versicolor,  56:  Virginica,  57: Versicolor,  5

## 2. One vs One

#### Prepare Train Lebel

In [7]:
trainX_AB = trainX[:100]
trainX_BC = trainX[50:]
trainX_AC = trainX.drop(range(50, 100))

trainY = np.append(np.ones(50), -np.ones(50))

#### Make SVM Model and Fit

In [8]:
C = 10

svm_model_AB = svm.SVC(kernel = 'linear', C=C).fit(trainX_AB, trainY)
svm_model_BC = svm.SVC(kernel = 'linear', C=C).fit(trainX_BC, trainY)
svm_model_AC = svm.SVC(kernel = 'linear', C=C).fit(trainX_AC, trainY)

predY_AB = svm_model_AB.predict(trainX_AB)
predY_BC = svm_model_BC.predict(trainX_BC)
predY_AC = svm_model_AC.predict(trainX_AC)

#### Result

In [9]:
# Confusion Matrix 출력
print(confusion_matrix(trainY, predY_AB))
print(confusion_matrix(trainY, predY_BC))
print(confusion_matrix(trainY, predY_AC))

[[50  0]
 [ 0 50]]
[[50  0]
 [ 3 47]]
[[50  0]
 [ 0 50]]


In [10]:
# 멀티클래스에 대해 분류
predAB = svm_model_AB.predict(trainX)
predBC = svm_model_BC.predict(trainX)
predAC = svm_model_AC.predict(trainX)

predAB[predAB == 1] = 0
predAB[predAB == -1] = 1
predBC[predBC == 1] = 1
predBC[predBC == -1] = 2
predAC[predAC == 1] = 0
predAC[predAC == -1] = 2
# 0: Setosa, 1: Versicolor, 2: Virginica

predMulti = np.reshape(np.concatenate((predAB, predBC, predAC), axis=0), (3, 150)).T

In [11]:
for i in range(predMulti.shape[0]):
    count = np.array([0, 0, 0])
    for j in range(predMulti.shape[1]):
        if predMulti[i][j] == 0:
            count[0] += 1
        elif predMulti[i][j] == 1:
            count[1] += 1
        else:
            count[2] += 1
            
    print("%3d: %10s" %(i ,class_name[np.argmax(count)]), end=", ")
    
    if (i+1) % 5 == 0:
        print("")
        if (i+1) % 50 == 0:
            print("")

  0:     Setosa,   1:     Setosa,   2:     Setosa,   3:     Setosa,   4:     Setosa, 
  5:     Setosa,   6:     Setosa,   7:     Setosa,   8:     Setosa,   9:     Setosa, 
 10:     Setosa,  11:     Setosa,  12:     Setosa,  13:     Setosa,  14:     Setosa, 
 15:     Setosa,  16:     Setosa,  17:     Setosa,  18:     Setosa,  19:     Setosa, 
 20:     Setosa,  21:     Setosa,  22:     Setosa,  23:     Setosa,  24:     Setosa, 
 25:     Setosa,  26:     Setosa,  27:     Setosa,  28:     Setosa,  29:     Setosa, 
 30:     Setosa,  31:     Setosa,  32:     Setosa,  33:     Setosa,  34:     Setosa, 
 35:     Setosa,  36:     Setosa,  37:     Setosa,  38:     Setosa,  39:     Setosa, 
 40:     Setosa,  41:     Setosa,  42:     Setosa,  43:     Setosa,  44:     Setosa, 
 45:     Setosa,  46:     Setosa,  47:     Setosa,  48:     Setosa,  49:     Setosa, 

 50: Versicolor,  51: Versicolor,  52: Versicolor,  53: Versicolor,  54: Versicolor, 
 55: Versicolor,  56: Versicolor,  57: Versicolor,  5